package com.mweis.pathfinder.engine.entity.components;

import com.badlogic.ashley.core.Component;

public class InputComponent implements Component {
	/*
	 * UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED
	 * UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED
	 * UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED
	 * UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED
	 * UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED
	 * UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED UNUSED
	 */
}
